* setup
(require 'ob-org)
(require 'ob-python)
** stdout/stderr on bad exit-code
#+BEGIN_SRC elisp
(defun org-babel-eval (cmd body)
  "Run CMD on BODY.
If CMD succeeds then return its results, otherwise display
STDERR with `org-babel-eval-error-notify'."
(prin1 cmd)
  (let ((err-buff (get-buffer-create " *Org-Babel Error*")) exit-code)
    (with-current-buffer err-buff (erase-buffer))
    (with-temp-buffer
      (insert body)
      (setq exit-code
	    (org-babel--shell-command-on-region
	     (point-min) (point-max) cmd err-buff))
      (if (or (not (numberp exit-code)) (> exit-code 0))
	  (progn
	    (with-current-buffer err-buff
	      (org-babel-eval-error-notify exit-code (buffer-string)))
	    (save-excursion
	      (when (get-buffer org-babel-error-buffer-name)
		(with-current-buffer org-babel-error-buffer-name
		  (unless (derived-mode-p 'compilation-mode)
		    (compilation-mode))
		  ;; Compilation-mode enforces read-only, but Babel expects the buffer modifiable.
		  (setq buffer-read-only nil))))
	    (concat (buffer-string) "STDERR:\n" (with-current-buffer err-buff (buffer-string))))
	(buffer-string)))))
#+END_SRC
* make work
 - tangle file: C-c C-v t
 - C-c C-c code src

** foo
#+BEGIN_SRC cpp :results output
#include <stdio.h>
int main() {
  printf("sdf\n");
  int foo[10];
  foo[11] = 2;
  printf("z\n");
  return 0;
}
#+END_SRC

#+RESULTS:
: STDERR:
: *** stack smashing detected ***: terminated

* day 1
** puzzle
--- Day 1: Sonar Sweep ---

You're minding your own business on a ship at sea when the overboard alarm goes off! You rush to see if you can help. Apparently, one of the Elves tripped and accidentally sent the sleigh keys flying into the ocean!

Before you know it, you're inside a submarine the Elves keep ready for situations like this. It's covered in Christmas lights (because of course it is), and it even has an experimental antenna that should be able to track the keys if you can boost its signal strength high enough; there's a little meter that indicates the antenna's signal strength by displaying 0-50 stars.

Your instincts tell you that in order to save Christmas, you'll need to get all fifty stars by December 25th.

Collect stars by solving puzzles. Two puzzles will be made available on each day in the Advent calendar; the second puzzle is unlocked when you complete the first. Each puzzle grants one star. Good luck!

As the submarine drops below the surface of the ocean, it automatically performs a sonar sweep of the nearby sea floor. On a small screen, the sonar sweep report (your puzzle input) appears: each line is a measurement of the sea floor depth as the sweep looks further and further away from the submarine.

For example, suppose you had the following report:

199
200
208
210
200
207
240
269
260
263

This report indicates that, scanning outward from the submarine, the sonar sweep found depths of 199, 200, 208, 210, and so on.

The first order of business is to figure out how quickly the depth increases, just so you know what you're dealing with - you never know if the keys will get carried into deeper water by an ocean current or a fish or something.

To do this, count the number of times a depth measurement increases from the previous measurement. (There is no measurement before the first measurement.) In the example above, the changes are as follows:

199 (N/A - no previous measurement)
200 (increased)
208 (increased)
210 (increased)
200 (decreased)
207 (increased)
240 (increased)
269 (increased)
260 (decreased)
263 (increased)

In this example, there are 7 measurements that are larger than the previous measurement.

How many measurements are larger than the previous measurement?

Your puzzle answer was 1167.
--- Part Two ---

Considering every single measurement isn't as useful as you expected: there's just too much noise in the data.

Instead, consider sums of a three-measurement sliding window. Again considering the above example:

199  A      
200  A B    
208  A B C  
210    B C D
200  E   C D
207  E F   D
240  E F G  
269    F G H
260      G H
263        H

Start by comparing the first and second three-measurement windows. The measurements in the first window are marked A (199, 200, 208); their sum is 199 + 200 + 208 = 607. The second window is marked B (200, 208, 210); its sum is 618. The sum of measurements in the second window is larger than the sum of the first, so this first comparison increased.

Your goal now is to count the number of times the sum of measurements in this sliding window increases from the previous sum. So, compare A with B, then compare B with C, then C with D, and so on. Stop when there aren't enough measurements left to create a new three-measurement sum.

In the above example, the sum of each three-measurement window is as follows:

A: 607 (N/A - no previous sum)
B: 618 (increased)
C: 618 (no change)
D: 617 (decreased)
E: 647 (increased)
F: 716 (increased)
G: 769 (increased)
H: 792 (increased)

In this example, there are 5 sums that are larger than the previous sum.

Consider sums of a three-measurement sliding window. How many sums are larger than the previous sum?

Your puzzle answer was 1130.

Both parts of this puzzle are complete! They provide two gold stars: **
** star 1
 - <2021-12-02 Thu 18:15>
#+BEGIN_SRC cpp :results output
#include <stdio.h>

int main() {
  FILE *f = fopen("01.txt", "r");
  int increases = 0;
  int prev = -1;
  int cur;
  while (1 == fscanf(f, "%d", &cur)) {
    if (prev != -1 && cur > prev)
      increases++;
    prev = cur;
  }
  printf("= %d\n", increases);
  return 0;
}
#+END_SRC

#+RESULTS:
: = 1167
 - <2021-12-02 Thu 18:17>

** star 2
#+BEGIN_SRC cpp :results output
#include <stdio.h>

int main() {
  FILE *f = fopen("01.txt", "r");
  int increases = 0;
  int prevprevprev = -1;
  int prevprev = -1;
  int prev = -1;
  int cur;
  while (1 == fscanf(f, "%d", &cur)) {
    if (prev != -1 && prevprev != -1 && prevprevprev != -1 && prevprev + prev + cur > prevprevprev + prevprev + prev)
      increases++;
    prevprevprev = prevprev;
    prevprev = prev;
    prev = cur;
  }
  printf("= %d\n", increases);
  return 0;
}
#+END_SRC

#+RESULTS:
: = 1130
 - <2021-12-02 Thu 18:21>
* day 2
** puzzle
--- Day 2: Dive! ---

Now, you need to figure out how to pilot this thing.

It seems like the submarine can take a series of commands like forward 1, down 2, or up 3:

    forward X increases the horizontal position by X units.
    down X increases the depth by X units.
    up X decreases the depth by X units.

Note that since you're on a submarine, down and up affect your depth, and so they have the opposite result of what you might expect.

The submarine seems to already have a planned course (your puzzle input). You should probably figure out where it's going. For example:

forward 5
down 5
forward 8
up 3
down 8
forward 2

Your horizontal position and depth both start at 0. The steps above would then modify them as follows:

    forward 5 adds 5 to your horizontal position, a total of 5.
    down 5 adds 5 to your depth, resulting in a value of 5.
    forward 8 adds 8 to your horizontal position, a total of 13.
    up 3 decreases your depth by 3, resulting in a value of 2.
    down 8 adds 8 to your depth, resulting in a value of 10.
    forward 2 adds 2 to your horizontal position, a total of 15.

After following these instructions, you would have a horizontal position of 15 and a depth of 10. (Multiplying these together produces 150.)

Calculate the horizontal position and depth you would have after following the planned course. What do you get if you multiply your final horizontal position by your final depth?

Your puzzle answer was 1989014.
--- Part Two ---

Based on your calculations, the planned course doesn't seem to make any sense. You find the submarine manual and discover that the process is actually slightly more complicated.

In addition to horizontal position and depth, you'll also need to track a third value, aim, which also starts at 0. The commands also mean something entirely different than you first thought:

    down X increases your aim by X units.
    up X decreases your aim by X units.
    forward X does two things:
        It increases your horizontal position by X units.
        It increases your depth by your aim multiplied by X.

Again note that since you're on a submarine, down and up do the opposite of what you might expect: "down" means aiming in the positive direction.

Now, the above example does something different:

    forward 5 adds 5 to your horizontal position, a total of 5. Because your aim is 0, your depth does not change.
    down 5 adds 5 to your aim, resulting in a value of 5.
    forward 8 adds 8 to your horizontal position, a total of 13. Because your aim is 5, your depth increases by 8*5=40.
    up 3 decreases your aim by 3, resulting in a value of 2.
    down 8 adds 8 to your aim, resulting in a value of 10.
    forward 2 adds 2 to your horizontal position, a total of 15. Because your aim is 10, your depth increases by 2*10=20 to a total of 60.

After following these new instructions, you would have a horizontal position of 15 and a depth of 60. (Multiplying these produces 900.)

Using this new interpretation of the commands, calculate the horizontal position and depth you would have after following the planned course. What do you get if you multiply your final horizontal position by your final depth?

Your puzzle answer was 2006917119.

Both parts of this puzzle are complete! They provide two gold stars: **
** star 1
  - <2021-12-02 Thu 18:23>
#+BEGIN_SRC cpp :results output
#include <stdio.h>
#include <stdlib.h>
int main() {
  FILE *f = fopen("02.txt", "r");
  int horpos = 0;
  int depth = 0;
  while (true) {
    int val;
    if (fscanf(f, "forward %d\n", &val) == 1) {
      horpos += val;
    } else if (fscanf(f, "down %d\n", &val) == 1) {
      depth += val;
    } else if (fscanf(f, "up %d\n", &val) == 1) {
      depth -= val;
    } else {
      break;
    }
  }

  printf("= %d\n", horpos * depth);
  return 0;
}
#+END_SRC

#+RESULTS:
: = 1989014
 - <2021-12-02 Thu 18:26>
** star 2
  - <2021-12-02 Thu 18:23>
#+BEGIN_SRC cpp :results output
#include <stdio.h>
#include <stdlib.h>
int main() {
  FILE *f = fopen("02.txt", "r");
  int horpos = 0;
  int depth = 0;
  int aim = 0;
  while (true) {
    int val;
    if (fscanf(f, "forward %d\n", &val) == 1) {
      horpos += val;
      depth += val * aim;
    } else if (fscanf(f, "down %d\n", &val) == 1) {
      aim += val;
    } else if (fscanf(f, "up %d\n", &val) == 1) {
      aim -= val;
    } else {
      break;
    }
  }

  printf("= %ld\n", (long)horpos * depth);
  return 0;
}
#+END_SRC

#+RESULTS:
: = 2006917119
 - <2021-12-02 Thu 18:28>

* day 3
** puzzle
--- Day 3: Binary Diagnostic ---

The submarine has been making some odd creaking noises, so you ask it to produce a diagnostic report just in case.

The diagnostic report (your puzzle input) consists of a list of binary numbers which, when decoded properly, can tell you many useful things about the conditions of the submarine. The first parameter to check is the power consumption.

You need to use the binary numbers in the diagnostic report to generate two new binary numbers (called the gamma rate and the epsilon rate). The power consumption can then be found by multiplying the gamma rate by the epsilon rate.

Each bit in the gamma rate can be determined by finding the most common bit in the corresponding position of all numbers in the diagnostic report. For example, given the following diagnostic report:

00100
11110
10110
10111
10101
01111
00111
11100
10000
11001
00010
01010

Considering only the first bit of each number, there are five 0 bits and seven 1 bits. Since the most common bit is 1, the first bit of the gamma rate is 1.

The most common second bit of the numbers in the diagnostic report is 0, so the second bit of the gamma rate is 0.

The most common value of the third, fourth, and fifth bits are 1, 1, and 0, respectively, and so the final three bits of the gamma rate are 110.

So, the gamma rate is the binary number 10110, or 22 in decimal.

The epsilon rate is calculated in a similar way; rather than use the most common bit, the least common bit from each position is used. So, the epsilon rate is 01001, or 9 in decimal. Multiplying the gamma rate (22) by the epsilon rate (9) produces the power consumption, 198.

Use the binary numbers in your diagnostic report to calculate the gamma rate and epsilon rate, then multiply them together. What is the power consumption of the submarine? (Be sure to represent your answer in decimal, not binary.)

Your puzzle answer was 3969000.
--- Part Two ---

Next, you should verify the life support rating, which can be determined by multiplying the oxygen generator rating by the CO2 scrubber rating.

Both the oxygen generator rating and the CO2 scrubber rating are values that can be found in your diagnostic report - finding them is the tricky part. Both values are located using a similar process that involves filtering out values until only one remains. Before searching for either rating value, start with the full list of binary numbers from your diagnostic report and consider just the first bit of those numbers. Then:

    Keep only numbers selected by the bit criteria for the type of rating value for which you are searching. Discard numbers which do not match the bit criteria.
    If you only have one number left, stop; this is the rating value for which you are searching.
    Otherwise, repeat the process, considering the next bit to the right.

The bit criteria depends on which type of rating value you want to find:

    To find oxygen generator rating, determine the most common value (0 or 1) in the current bit position, and keep only numbers with that bit in that position. If 0 and 1 are equally common, keep values with a 1 in the position being considered.
    To find CO2 scrubber rating, determine the least common value (0 or 1) in the current bit position, and keep only numbers with that bit in that position. If 0 and 1 are equally common, keep values with a 0 in the position being considered.

For example, to determine the oxygen generator rating value using the same example diagnostic report from above:

    Start with all 12 numbers and consider only the first bit of each number. There are more 1 bits (7) than 0 bits (5), so keep only the 7 numbers with a 1 in the first position: 11110, 10110, 10111, 10101, 11100, 10000, and 11001.
    Then, consider the second bit of the 7 remaining numbers: there are more 0 bits (4) than 1 bits (3), so keep only the 4 numbers with a 0 in the second position: 10110, 10111, 10101, and 10000.
    In the third position, three of the four numbers have a 1, so keep those three: 10110, 10111, and 10101.
    In the fourth position, two of the three numbers have a 1, so keep those two: 10110 and 10111.
    In the fifth position, there are an equal number of 0 bits and 1 bits (one each). So, to find the oxygen generator rating, keep the number with a 1 in that position: 10111.
    As there is only one number left, stop; the oxygen generator rating is 10111, or 23 in decimal.

Then, to determine the CO2 scrubber rating value from the same example above:

    Start again with all 12 numbers and consider only the first bit of each number. There are fewer 0 bits (5) than 1 bits (7), so keep only the 5 numbers with a 0 in the first position: 00100, 01111, 00111, 00010, and 01010.
    Then, consider the second bit of the 5 remaining numbers: there are fewer 1 bits (2) than 0 bits (3), so keep only the 2 numbers with a 1 in the second position: 01111 and 01010.
    In the third position, there are an equal number of 0 bits and 1 bits (one each). So, to find the CO2 scrubber rating, keep the number with a 0 in that position: 01010.
    As there is only one number left, stop; the CO2 scrubber rating is 01010, or 10 in decimal.

Finally, to find the life support rating, multiply the oxygen generator rating (23) by the CO2 scrubber rating (10) to get 230.

Use the binary numbers in your diagnostic report to calculate the oxygen generator rating and CO2 scrubber rating, then multiply them together. What is the life support rating of the submarine? (Be sure to represent your answer in decimal, not binary.)

Your puzzle answer was 4267809.

Both parts of this puzzle are complete! They provide two gold stars: **
** part 1
#+BEGIN_SRC cpp :results output
#include <stdio.h>
int main() {
  char line[256];
  long gamma = 0;
  long epsilon = 0;
  for (int i = 0; i < 12; i++) {
    gamma = gamma << 1;
    epsilon = epsilon << 1;
    FILE *f = fopen("03.txt", "r");
    int ones = 0;
    int zeros = 0;
    while (fgets(line, sizeof(line), f)) {
      if (line[i] == '1') ones++; else zeros++;
    }
    if (ones > zeros) {
      gamma += 1;
    } else {
      epsilon += 1;
    }
  }
  printf("= %ld\n", gamma * epsilon);
  return 0;
}
#+END_SRC

#+RESULTS:
: = 3969000

 - 16159416000 too high <2021-12-03 Fri 18:26>
 - 3969000 correct <2021-12-03 Fri 18:28>
** part 2
#+BEGIN_SRC cpp :results output
#include <stdio.h>
#define LEN 12
int main() {
  int numbers[1024];
  int numbersi = 0;
  char line[256];

  int oxygen = -1;

  {
  FILE *f = fopen("03.txt", "r");
  while (fgets(line, sizeof(line), f)) {
    int value = 0;
    for (int i = 0; line[i] == '0' || line[i] == '1'; i++) {
      value = value << 1;
      if (line[i] == '1') value += 1;
    }
    numbers[numbersi++] = value;
  }

  for (int i = LEN-1; i >= 0; i--) {
    int ones = 0, zeros = 0;
    for (int ni = 0; ni < numbersi; ni++) {
      if (numbers[ni] == -1) continue;
      if ((numbers[ni] & (1 << i)) >= 1) ones++; else zeros++;
      //printf("'%d' ones=%d, zeros=%d\n", numbers[ni], ones, zeros);
    }
    int found = -1;
    int founds = 0;
    for (int ni = 0; ni < numbersi; ni++) {
      if (numbers[ni] == -1) continue;
      if ((numbers[ni] & (1 << i)) >= 1 != (ones >= zeros) >= 1) numbers[ni] = -1;
      else { found = numbers[ni]; founds++; }
    }
    //printf("i=%d  ones=%d  zeros=%d  founds=%d\n", i, ones, zeros, founds);
    if (founds == 1) { oxygen = found; break; }
  }
  }
  

  int co2 = -1;
  numbersi = 0;
  {
  FILE *f = fopen("03.txt", "r");
  while (fgets(line, sizeof(line), f)) {
    int value = 0;
    for (int i = 0; line[i] == '0' || line[i] == '1'; i++) {
      value = value << 1;
      if (line[i] == '1') value += 1;
    }
    numbers[numbersi++] = value;
  }

  for (int i = LEN-1; i >= 0; i--) {
    int ones = 0, zeros = 0;
    for (int ni = 0; ni < numbersi; ni++) {
      if (numbers[ni] == -1) continue;
      if ((numbers[ni] & (1 << i)) >= 1) ones++; else zeros++;
      //printf("'%d' ones=%d, zeros=%d\n", numbers[ni], ones, zeros);
    }
    int found = -1;
    int founds = 0;
    for (int ni = 0; ni < numbersi; ni++) {
      if (numbers[ni] == -1) continue;
      if ((numbers[ni] & (1 << i)) >= 1 == (ones >= zeros) >= 1) numbers[ni] = -1;
      else { found = numbers[ni]; founds++; }
    }
    //printf("i=%d  ones=%d  zeros=%d  founds=%d\n", i, ones, zeros, founds);
    if (founds == 1) { co2 = found; break; }
  }
  }

  printf("o=%d  co2=%d\n", oxygen, co2);
  printf("= %ld\n", oxygen * co2);
  return 0;
}
#+END_SRC

#+RESULTS:
: o=2509  co2=1701
: = 4267809

 - 819540 too low <2021-12-03 Fri 18:48>
 - 4267809 correct <2021-12-03 Fri 18:58>
* day 4
** puzzle
** part 1
 - <2021-12-04 Sat 11:29>
#+BEGIN_SRC cpp :results output
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
int main() {
  int draws[1024];
  int drawsi = 0;

  char line[1024];
  FILE *f = fopen("04.txt", "r");
  {
    fgets(line, sizeof(line), f);
    line[strlen(line)-1] = 0;
    char *str1, *token, *saveptr;
    str1 = line;
    while (token = strtok_r(str1, ",", &saveptr)) {
      draws[drawsi++] = atoi(token);
      str1 = NULL;
    }
  }

  int boards[100][5][5];
  int boardsi = 0;

  while (fgets(line, sizeof(line), f)) {
    for (int i = 0; i < 5; i++) {
      fgets(line, sizeof(line), f);
      for (int j = 0; j < 5; j++) {
        boards[boardsi][i][j] = atoi(line + j*3);
      }
    }
    boardsi++;
  }
if (false) {
  for (int b = 0; b < boardsi; b++) {
    for (int i = 0; i < 5; i++) {
      for (int j = 0; j < 5; j++) {
        printf("%2d ", boards[b][i][j]);
      }
      printf("\n");
    }
    printf("\n");
  }
}

  for (int d = 0; d < drawsi; d++) {
    for (int b = 0; b < boardsi; b++) {
      for (int i = 0; i < 5; i++) {
        for (int j = 0; j < 5; j++) {
          if (boards[b][i][j] == draws[d]) {
            boards[b][i][j] = -1;
          }
        }
      }
    }
if (false) {
  printf("## draw %d\n", draws[d]);
  for (int b = 0; b < boardsi; b++) {
    for (int i = 0; i < 5; i++) {
      for (int j = 0; j < 5; j++) {
        printf("%2d ", boards[b][i][j]);
      }
      printf("\n");
    }
    printf("\n");
  }
}
    
    for (int b = 0; b < boardsi; b++) {
      int bingoboard = false;
      for (int i = 0; i < 5; i++) {
        int bingo = true;
        for (int j = 0; j < 5; j++) {
          if (boards[b][i][j] != -1) bingo = false;
        }
        if (bingo) bingoboard = true;
      }
      for (int j = 0; j < 5; j++) {
        int bingo = true;
        for (int i = 0; i < 5; i++) {
          if (boards[b][i][j] != -1) bingo = false;
        }
        if (bingo) bingoboard = true;
      }
      if (bingoboard) {
        int unmarkedsum = 0;
        for (int i = 0; i < 5; i++) {
          for (int j = 0; j < 5; j++) {
            if (boards[b][i][j] != -1) unmarkedsum += boards[b][i][j];
          }
        }
        printf("= %d\n", unmarkedsum*draws[d]);
        return 0;
      }
    }
  }
  return 0;
}
#+END_SRC

#+RESULTS:
: = 16716

 - 16716 correct <2021-12-04 Sat 12:01>
** part 2
#+BEGIN_SRC cpp :results output
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
int main() {
  int draws[1024];
  int drawsi = 0;

  char line[1024];
  FILE *f = fopen("04.txt", "r");
  {
    fgets(line, sizeof(line), f);
    line[strlen(line)-1] = 0;
    char *str1, *token, *saveptr;
    str1 = line;
    while (token = strtok_r(str1, ",", &saveptr)) {
      draws[drawsi++] = atoi(token);
      str1 = NULL;
    }
  }

  int boards[100][5][5];
  int boardsi = 0;

  while (fgets(line, sizeof(line), f)) {
    for (int i = 0; i < 5; i++) {
      fgets(line, sizeof(line), f);
      for (int j = 0; j < 5; j++) {
        boards[boardsi][i][j] = atoi(line + j*3);
      }
    }
    boardsi++;
  }
if (false) {
  for (int b = 0; b < boardsi; b++) {
    for (int i = 0; i < 5; i++) {
      for (int j = 0; j < 5; j++) {
        printf("%2d ", boards[b][i][j]);
      }
      printf("\n");
    }
    printf("\n");
  }
}

  int won[1024];
  for (int b = 0; b < boardsi; b++) {
    won[b] = false;
  }
  int wons = 0;

  for (int d = 0; d < drawsi; d++) {
    for (int b = 0; b < boardsi; b++) {
      for (int i = 0; i < 5; i++) {
        for (int j = 0; j < 5; j++) {
          if (boards[b][i][j] == draws[d]) {
            boards[b][i][j] = -1;
          }
        }
      }
    }
if (false) {
  printf("## draw %d\n", draws[d]);
  for (int b = 0; b < boardsi; b++) {
    for (int i = 0; i < 5; i++) {
      for (int j = 0; j < 5; j++) {
        printf("%2d ", boards[b][i][j]);
      }
      printf("\n");
    }
    printf("\n");
  }
}
    
    for (int b = 0; b < boardsi; b++) {
      if (won[b]) continue;
      int bingoboard = false;
      for (int i = 0; i < 5; i++) {
        int bingo = true;
        for (int j = 0; j < 5; j++) {
          if (boards[b][i][j] != -1) bingo = false;
        }
        if (bingo) bingoboard = true;
      }
      for (int j = 0; j < 5; j++) {
        int bingo = true;
        for (int i = 0; i < 5; i++) {
          if (boards[b][i][j] != -1) bingo = false;
        }
        if (bingo) bingoboard = true;
      }
      if (bingoboard) {
        won[b] = true;
        wons++;
        if (wons != boardsi) continue;
        int unmarkedsum = 0;
        for (int i = 0; i < 5; i++) {
          for (int j = 0; j < 5; j++) {
            if (boards[b][i][j] != -1) unmarkedsum += boards[b][i][j];
          }
        }
        printf("= %d\n", unmarkedsum*draws[d]);
        return 0;
      }
    }
  }
  return 0;
}
#+END_SRC

#+RESULTS:
: = 4880

- 4880 correct <2021-12-04 Sat 12:04>

* day 5
** puzzle
--- Day 5: Hydrothermal Venture ---

You come across a field of hydrothermal vents on the ocean floor! These vents constantly produce large, opaque clouds, so it would be best to avoid them if possible.

They tend to form in lines; the submarine helpfully produces a list of nearby lines of vents (your puzzle input) for you to review. For example:

0,9 -> 5,9
8,0 -> 0,8
9,4 -> 3,4
2,2 -> 2,1
7,0 -> 7,4
6,4 -> 2,0
0,9 -> 2,9
3,4 -> 1,4
0,0 -> 8,8
5,5 -> 8,2

Each line of vents is given as a line segment in the format x1,y1 -> x2,y2 where x1,y1 are the coordinates of one end the line segment and x2,y2 are the coordinates of the other end. These line segments include the points at both ends. In other words:

    An entry like 1,1 -> 1,3 covers points 1,1, 1,2, and 1,3.
    An entry like 9,7 -> 7,7 covers points 9,7, 8,7, and 7,7.

For now, only consider horizontal and vertical lines: lines where either x1 = x2 or y1 = y2.

So, the horizontal and vertical lines from the above list would produce the following diagram:

.......1..
..1....1..
..1....1..
.......1..
.112111211
..........
..........
..........
..........
222111....

In this diagram, the top left corner is 0,0 and the bottom right corner is 9,9. Each position is shown as the number of lines which cover that point or . if no line covers that point. The top-left pair of 1s, for example, comes from 2,2 -> 2,1; the very bottom row is formed by the overlapping lines 0,9 -> 5,9 and 0,9 -> 2,9.

To avoid the most dangerous areas, you need to determine the number of points where at least two lines overlap. In the above example, this is anywhere in the diagram with a 2 or larger - a total of 5 points.

Consider only horizontal and vertical lines. At how many points do at least two lines overlap?

Your puzzle answer was 5145.
--- Part Two ---

Unfortunately, considering only horizontal and vertical lines doesn't give you the full picture; you need to also consider diagonal lines.

Because of the limits of the hydrothermal vent mapping system, the lines in your list will only ever be horizontal, vertical, or a diagonal line at exactly 45 degrees. In other words:

    An entry like 1,1 -> 3,3 covers points 1,1, 2,2, and 3,3.
    An entry like 9,7 -> 7,9 covers points 9,7, 8,8, and 7,9.

Considering all lines from the above example would now produce the following diagram:

1.1....11.
.111...2..
..2.1.111.
...1.2.2..
.112313211
...1.2....
..1...1...
.1.....1..
1.......1.
222111....

You still need to determine the number of points where at least two lines overlap. In the above example, this is still anywhere in the diagram with a 2 or larger - now a total of 12 points.

Consider all of the lines. At how many points do at least two lines overlap?

Your puzzle answer was 16518.

Both parts of this puzzle are complete! They provide two gold stars: **
** part 1
 - <2021-12-05 Sun 07:26>
#+BEGIN_SRC cpp :results output
#include <stdio.h>
#define MAX 1000
int main() {
  int grid[MAX][MAX] = { 0 };

  FILE *f = fopen("05.txt", "r");
  int x1, y1, x2, y2;
  int tmp;
  while (fscanf(f, "%d,%d -> %d,%d\n", &x1, &y1, &x2, &y2) == 4) {
    if (x1 == x2) {
      if (y1 > y2) { tmp = y1; y1 = y2; y2 = tmp; }
      for (int y = y1; y <= y2; y++)
        grid[y][x1]++;
    }
    if (y1 == y2) {
      if (x1 > x2) { tmp = x1; x1 = x2; x2 = tmp; }
      for (int x = x1; x <= x2; x++)
        grid[y1][x]++;
    }
  }

  int overlaps = 0;
  for (int y = 0; y < MAX; y++) 
    for (int x = 0; x < MAX; x++)
      if (grid[y][x] >= 2)
        overlaps++;

  if (false)
  for (int y = 0; y < MAX; y++) {
    for (int x = 0; x < MAX; x++) {
      printf("%c", grid[y][x] == 0 ? '.' : '0'+grid[y][x]);
    }
    printf("\n");
  }


  printf("= %d\n", overlaps);
  return 0;
}
#+END_SRC 

#+RESULTS:
: = 5145

 - 10140 too high <2021-12-05 Sun 07:34>
 - 9526 too high <2021-12-05 Sun 07:37>
 - 5145 correct <2021-12-05 Sun 07:38>
** part 2
#+BEGIN_SRC cpp :results output
#include <stdio.h>
#define MAX 1000
int main() {
  int grid[MAX][MAX] = { 0 };

  FILE *f = fopen("05.txt", "r");
  int x1, y1, x2, y2;
  int tmp;
  while (fscanf(f, "%d,%d -> %d,%d\n", &x1, &y1, &x2, &y2) == 4) {
    int x = x1, y = y1;
      grid[y][x]++;
    do {
      if (x < x2) x++; else if (x > x2) x--;
      if (y < y2) y++; else if (y > y2) y--;
      grid[y][x]++;
    } while (x != x2 || y != y2);
    //printf("## %d,%d -> %d,%d\n", x1, y1, x2, y2);
  if (false)
  for (int y = 0; y < MAX; y++) {
    for (int x = 0; x < MAX; x++) {
      printf("%c", grid[y][x] == 0 ? '.' : '0'+grid[y][x]);
    }
    printf("\n");
  }
  }

  int overlaps = 0;
  for (int y = 0; y < MAX; y++) 
    for (int x = 0; x < MAX; x++)
      if (grid[y][x] >= 2)
        overlaps++;

  if (false)
  for (int y = 0; y < MAX; y++) {
    for (int x = 0; x < MAX; x++) {
      printf("%c", grid[y][x] == 0 ? '.' : '0'+grid[y][x]);
    }
    printf("\n");
  }


  printf("= %d\n", overlaps);
  return 0;
}
#+END_SRC 

#+RESULTS:
: = 16518

 - 7074 too low <2021-12-05 Sun 07:40>
 - 16518 correct <2021-12-05 Sun 07:48>
