* setup
(require 'ob-org)
(require 'ob-python)
** stdout/stderr on bad exit-code
#+BEGIN_SRC elisp
(defun org-babel-eval (cmd body)
  "Run CMD on BODY.
If CMD succeeds then return its results, otherwise display
STDERR with `org-babel-eval-error-notify'."
  (let ((err-buff (get-buffer-create " *Org-Babel Error*")) exit-code)
    (with-current-buffer err-buff (erase-buffer))
    (with-temp-buffer
      (insert body)
      (setq exit-code
	    (org-babel--shell-command-on-region
	     (point-min) (point-max) cmd err-buff))
      (if (or (not (numberp exit-code)) (> exit-code 0))
	  (progn
	    (with-current-buffer err-buff
	      (org-babel-eval-error-notify exit-code (buffer-string)))
	    (save-excursion
	      (when (get-buffer org-babel-error-buffer-name)
		(with-current-buffer org-babel-error-buffer-name
		  (unless (derived-mode-p 'compilation-mode)
		    (compilation-mode))
		  ;; Compilation-mode enforces read-only, but Babel expects the buffer modifiable.
		  (setq buffer-read-only nil))))
	    (concat (buffer-string) "STDERR:\n" (with-current-buffer err-buff (buffer-string))))
	(buffer-string)))))
#+END_SRC
* make work
 - tangle file: C-c C-v t
 - C-c C-c code src

* day 1
** puzzle
--- Day 1: The Tyranny of the Rocket Equation ---

Santa has become stranded at the edge of the Solar System while delivering presents to other planets! To accurately calculate his position in space, safely align his warp drive, and return to Earth in time to save Christmas, he needs you to bring him measurements from fifty stars.

Collect stars by solving puzzles. Two puzzles will be made available on each day in the Advent calendar; the second puzzle is unlocked when you complete the first. Each puzzle grants one star. Good luck!

The Elves quickly load you into a spacecraft and prepare to launch.

At the first Go / No Go poll, every Elf is Go until the Fuel Counter-Upper. They haven't determined the amount of fuel required yet.

Fuel required to launch a given module is based on its mass. Specifically, to find the fuel required for a module, take its mass, divide by three, round down, and subtract 2.

For example:

    For a mass of 12, divide by 3 and round down to get 4, then subtract 2 to get 2.
    For a mass of 14, dividing by 3 and rounding down still yields 4, so the fuel required is also 2.
    For a mass of 1969, the fuel required is 654.
    For a mass of 100756, the fuel required is 33583.

The Fuel Counter-Upper needs to know the total fuel requirement. To find it, individually calculate the fuel needed for the mass of each module (your puzzle input), then add together all the fuel values.

What is the sum of the fuel requirements for all of the modules on your spacecraft?

Your puzzle answer was 3360301.
--- Part Two ---

During the second Go / No Go poll, the Elf in charge of the Rocket Equation Double-Checker stops the launch sequence. Apparently, you forgot to include additional fuel for the fuel you just added.

Fuel itself requires fuel just like a module - take its mass, divide by three, round down, and subtract 2. However, that fuel also requires fuel, and that fuel requires fuel, and so on. Any mass that would require negative fuel should instead be treated as if it requires zero fuel; the remaining mass, if any, is instead handled by wishing really hard, which has no mass and is outside the scope of this calculation.

So, for each module mass, calculate its fuel and add it to the total. Then, treat the fuel amount you just calculated as the input mass and repeat the process, continuing until a fuel requirement is zero or negative. For example:

    A module of mass 14 requires 2 fuel. This fuel requires no further fuel (2 divided by 3 and rounded down is 0, which would call for a negative fuel), so the total fuel required is still just 2.
    At first, a module of mass 1969 requires 654 fuel. Then, this fuel requires 216 more fuel (654 / 3 - 2). 216 then requires 70 more fuel, which requires 21 fuel, which requires 5 fuel, which requires no further fuel. So, the total fuel required for a module of mass 1969 is 654 + 216 + 70 + 21 + 5 = 966.
    The fuel required by a module of mass 100756 and its fuel is: 33583 + 11192 + 3728 + 1240 + 411 + 135 + 43 + 12 + 2 = 50346.

What is the sum of the fuel requirements for all of the modules on your spacecraft when also taking into account the mass of the added fuel? (Calculate the fuel requirements for each module separately, then add them all up at the end.)

Your puzzle answer was 5037595.

Both parts of this puzzle are complete! They provide two gold stars: **
** star 1
 - <2019-12-01 Sun 08:53>
#+BEGIN_SRC cpp :results output
#include <stdio.h>
int main(int argc, char** args) {
  FILE *f = fopen("01.txt", "r");

  int fuelsum = 0;
  int mass = -1;
  while (1 == fscanf(f, "%d\n", &mass)) {
    int fuel = (int) (mass / 3) - 2;
    fuelsum += fuel;
  }
  printf("= %d\n", fuelsum);
}
#+END_SRC

#+RESULTS:
: = 3360301
 - <2019-12-01 Sun 09:00>
** star 2
 - <2019-12-01 Sun>
#+BEGIN_SRC cpp :results output
  #include <stdio.h>
  int main(int argc, char** args) {
    FILE *f = fopen("01.txt", "r");

    int sum = 0;
    int mass;
    while (1 == fscanf(f, "%d\n", &mass)) {
      int fuelsum = 0;
      while (mass > 0) {
        int fuel = (int) (mass / 3) - 2;
        if (fuel > 0) {
          fuelsum += fuel;
        }
        mass = fuel;
      }
      sum += fuelsum;
    }
    printf("= %d\n", sum);
  }
#+END_SRC

#+RESULTS:
: = 5037595
 - <2019-12-01 Sun 09:05>
* day 2
** puzzle
--- Day 2: 1202 Program Alarm ---

On the way to your gravity assist around the Moon, your ship computer beeps angrily about a "1202 program alarm". On the radio, an Elf is already explaining how to handle the situation: "Don't worry, that's perfectly norma--" The ship computer bursts into flames.

You notify the Elves that the computer's magic smoke seems to have escaped. "That computer ran Intcode programs like the gravity assist program it was working on; surely there are enough spare parts up there to build a new Intcode computer!"

An Intcode program is a list of integers separated by commas (like 1,0,0,3,99). To run one, start by looking at the first integer (called position 0). Here, you will find an opcode - either 1, 2, or 99. The opcode indicates what to do; for example, 99 means that the program is finished and should immediately halt. Encountering an unknown opcode means something went wrong.

Opcode 1 adds together numbers read from two positions and stores the result in a third position. The three integers immediately after the opcode tell you these three positions - the first two indicate the positions from which you should read the input values, and the third indicates the position at which the output should be stored.

For example, if your Intcode computer encounters 1,10,20,30, it should read the values at positions 10 and 20, add those values, and then overwrite the value at position 30 with their sum.

Opcode 2 works exactly like opcode 1, except it multiplies the two inputs instead of adding them. Again, the three integers after the opcode indicate where the inputs and outputs are, not their values.

Once you're done processing an opcode, move to the next one by stepping forward 4 positions.

For example, suppose you have the following program:

1,9,10,3,2,3,11,0,99,30,40,50

For the purposes of illustration, here is the same program split into multiple lines:

1,9,10,3,
2,3,11,0,
99,
30,40,50

The first four integers, 1,9,10,3, are at positions 0, 1, 2, and 3. Together, they represent the first opcode (1, addition), the positions of the two inputs (9 and 10), and the position of the output (3). To handle this opcode, you first need to get the values at the input positions: position 9 contains 30, and position 10 contains 40. Add these numbers together to get 70. Then, store this value at the output position; here, the output position (3) is at position 3, so it overwrites itself. Afterward, the program looks like this:

1,9,10,70,
2,3,11,0,
99,
30,40,50

Step forward 4 positions to reach the next opcode, 2. This opcode works just like the previous, but it multiplies instead of adding. The inputs are at positions 3 and 11; these positions contain 70 and 50 respectively. Multiplying these produces 3500; this is stored at position 0:

3500,9,10,70,
2,3,11,0,
99,
30,40,50

Stepping forward 4 more positions arrives at opcode 99, halting the program.

Here are the initial and final states of a few more small programs:

    1,0,0,0,99 becomes 2,0,0,0,99 (1 + 1 = 2).
    2,3,0,3,99 becomes 2,3,0,6,99 (3 * 2 = 6).
    2,4,4,5,99,0 becomes 2,4,4,5,99,9801 (99 * 99 = 9801).
    1,1,1,4,99,5,6,0,99 becomes 30,1,1,4,2,5,6,0,99.

Once you have a working computer, the first step is to restore the gravity assist program (your puzzle input) to the "1202 program alarm" state it had just before the last computer caught fire. To do this, before running the program, replace position 1 with the value 12 and replace position 2 with the value 2. What value is left at position 0 after the program halts?

Your puzzle answer was 4945026.
--- Part Two ---

"Good, the new computer seems to be working correctly! Keep it nearby during this mission - you'll probably use it again. Real Intcode computers support many more features than your new one, but we'll let you know what they are as you need them."

"However, your current priority should be to complete your gravity assist around the Moon. For this mission to succeed, we should settle on some terminology for the parts you've already built."

Intcode programs are given as a list of integers; these values are used as the initial state for the computer's memory. When you run an Intcode program, make sure to start by initializing memory to the program's values. A position in memory is called an address (for example, the first value in memory is at "address 0").

Opcodes (like 1, 2, or 99) mark the beginning of an instruction. The values used immediately after an opcode, if any, are called the instruction's parameters. For example, in the instruction 1,2,3,4, 1 is the opcode; 2, 3, and 4 are the parameters. The instruction 99 contains only an opcode and has no parameters.

The address of the current instruction is called the instruction pointer; it starts at 0. After an instruction finishes, the instruction pointer increases by the number of values in the instruction; until you add more instructions to the computer, this is always 4 (1 opcode + 3 parameters) for the add and multiply instructions. (The halt instruction would increase the instruction pointer by 1, but it halts the program instead.)

"With terminology out of the way, we're ready to proceed. To complete the gravity assist, you need to determine what pair of inputs produces the output 19690720."

The inputs should still be provided to the program by replacing the values at addresses 1 and 2, just like before. In this program, the value placed in address 1 is called the noun, and the value placed in address 2 is called the verb. Each of the two input values will be between 0 and 99, inclusive.

Once the program has halted, its output is available at address 0, also just like before. Each time you try a pair of inputs, make sure you first reset the computer's memory to the values in the program (your puzzle input) - in other words, don't reuse memory from a previous attempt.

Find the input noun and verb that cause the program to produce the output 19690720. What is 100 * noun + verb? (For example, if noun=12 and verb=2, the answer would be 1202.)

Your puzzle answer was 5296.

Both parts of this puzzle are complete! They provide two gold stars: **
** part 1
 - <2019-12-02 Mon 20:19>
#+BEGIN_SRC cpp :results output
  #include <stdio.h>
  int main(int argc, char **args) {
      int positions[100000];
      FILE *f = fopen("02.txt", "r");

      for (int i = 0; i < 10000; i++) {
          if (fscanf(f, "%d", &positions[i]) != 1) {
              break;
          }
          fscanf(f, ",");
      }

      positions[1] = 12;
      positions[2] = 2;

      // int k = 0;
      // positions[k++] = 1;
      // positions[k++] = 1;
      // positions[k++] = 1;
      // positions[k++] = 4;
      // positions[k++] = 99;
      // positions[k++] = 5;
      // positions[k++] = 6;
      // positions[k++] = 0;
      // positions[k++] = 99;

      // int k = 0;
      // positions[k++] = 1;
      // positions[k++] = 0;
      // positions[k++] = 0;
      // positions[k++] = 0;
      // positions[k++] = 99;

      for (int i = 0; i < 10000; i += 4) {
        if (positions[i] == 99) {
          break;
        } else if (positions[i] == 1) {
          positions[positions[i+3]] = positions[positions[i+1]] + positions[positions[i+2]];
        } else if (positions[i] == 2) {
          positions[positions[i+3]] = positions[positions[i+1]] * positions[positions[i+2]];
        } else {
          printf("Error: %d: %d\n", i, positions[i]);
          return 0;
        }
      }

      printf("= %d\n", positions[0]);
      return 0;
  }
#+END_SRC

#+RESULTS:
: = 4945026

 - 145 too low <2019-12-02 Mon 20:37>
 - 4945026 <2019-12-02 Mon 20:40>
** part 2
 - <2019-12-02 Mon 20:41>
#+BEGIN_SRC cpp :results output
  #include <stdio.h>
  #define MAX 100000

  int run(int program[]) {
    int p[MAX];
    for (int i = 0; i < MAX; i++) {
      p[i] = program[i];
    }

      for (int i = 0; i < 10000; i += 4) {
        if (p[i] == 99) {
          break;
        } else if (p[i] == 1) {
          p[p[i+3]] = p[p[i+1]] + p[p[i+2]];
        } else if (p[i] == 2) {
          p[p[i+3]] = p[p[i+1]] * p[p[i+2]];
        } else {
          printf("Error: %d: %d\n", i, p[i]);
          return 0;
        }
      }
      return p[0];
  }

  int main(int argc, char **args) {
      int positions[MAX];
      FILE *f = fopen("02.txt", "r");

      for (int i = 0; i < 10000; i++) {
          if (fscanf(f, "%d", &positions[i]) != 1) {
              break;
          }
          fscanf(f, ",");
      }

      for (int noun = 0; noun <= 99; noun++) {
        for (int verb = 0; verb <= 99; verb++) {
          positions[1] = noun;
          positions[2] = verb;
          if (run(positions) == 19690720) {
            printf("verb=%d, noun=%d\n", verb, noun);
            printf("= %d\n", 100 * noun + verb);
            return 0;
          }
        }
      }
      printf("Not found!");
      return 0;
  }
#+END_SRC

#+RESULTS:
: verb=96, noun=52
: = 5296

 - 499200 too high <2019-12-02 Mon 20:46>
 - 5296 right answer <2019-12-02 Mon 20:48>
* day 3
** puzzle
--- Day 3: Crossed Wires ---

The gravity assist was successful, and you're well on your way to the Venus refuelling station. During the rush back on Earth, the fuel management system wasn't completely installed, so that's next on the priority list.

Opening the front panel reveals a jumble of wires. Specifically, two wires are connected to a central port and extend outward on a grid. You trace the path each wire takes as it leaves the central port, one wire per line of text (your puzzle input).

The wires twist and turn, but the two wires occasionally cross paths. To fix the circuit, you need to find the intersection point closest to the central port. Because the wires are on a grid, use the Manhattan distance for this measurement. While the wires do technically cross right at the central port where they both start, this point does not count, nor does a wire count as crossing with itself.

For example, if the first wire's path is R8,U5,L5,D3, then starting from the central port (o), it goes right 8, up 5, left 5, and finally down 3:

...........
...........
...........
....+----+.
....|....|.
....|....|.
....|....|.
.........|.
.o-------+.
...........

Then, if the second wire's path is U7,R6,D4,L4, it goes up 7, right 6, down 4, and left 4:

...........
.+-----+...
.|.....|...
.|..+--X-+.
.|..|..|.|.
.|.-X--+.|.
.|..|....|.
.|.......|.
.o-------+.
...........

These wires cross at two locations (marked X), but the lower-left one is closer to the central port: its distance is 3 + 3 = 6.

Here are a few more examples:

    R75,D30,R83,U83,L12,D49,R71,U7,L72
    U62,R66,U55,R34,D71,R55,D58,R83 = distance 159
    R98,U47,R26,D63,R33,U87,L62,D20,R33,U53,R51
    U98,R91,D20,R16,D67,R40,U7,R15,U6,R7 = distance 135

What is the Manhattan distance from the central port to the closest intersection?

Your puzzle answer was 221.
--- Part Two ---

It turns out that this circuit is very timing-sensitive; you actually need to minimize the signal delay.

To do this, calculate the number of steps each wire takes to reach each intersection; choose the intersection where the sum of both wires' steps is lowest. If a wire visits a position on the grid multiple times, use the steps value from the first time it visits that position when calculating the total value of a specific intersection.

The number of steps a wire takes is the total number of grid squares the wire has entered to get to that location, including the intersection being considered. Again consider the example from above:

...........
.+-----+...
.|.....|...
.|..+--X-+.
.|..|..|.|.
.|.-X--+.|.
.|..|....|.
.|.......|.
.o-------+.
...........

In the above example, the intersection closest to the central port is reached after 8+5+5+2 = 20 steps by the first wire and 7+6+4+3 = 20 steps by the second wire for a total of 20+20 = 40 steps.

However, the top-right intersection is better: the first wire takes only 8+5+2 = 15 and the second wire takes only 7+6+2 = 15, a total of 15+15 = 30 steps.

Here are the best steps for the extra examples from above:

    R75,D30,R83,U83,L12,D49,R71,U7,L72
    U62,R66,U55,R34,D71,R55,D58,R83 = 610 steps
    R98,U47,R26,D63,R33,U87,L62,D20,R33,U53,R51
    U98,R91,D20,R16,D67,R40,U7,R15,U6,R7 = 410 steps

What is the fewest combined steps the wires must take to reach an intersection?

Your puzzle answer was 18542.

Both parts of this puzzle are complete! They provide two gold stars: **
** part 1
 - <2019-12-03 Tue 18:46>
#+BEGIN_SRC cpp :results output
  #include <stdio.h>
  #include <stdlib.h>
  #define BUF 30000
  int main(int argc, char **args) {
    // char grid[BUF][BUF] = { 0 };

    int **grid = (int **) malloc(BUF * sizeof(int *));
    for (int i = 0; i < BUF; i++) {
      grid[i] = (int *) malloc(BUF * sizeof(int));
      for (int j = 0; j < BUF; j++) {
        grid[i][j] = 0;
      }
    }

    FILE *f = fopen("03.txt", "r");
    int x = BUF/2;
    int y = BUF/2;
    while (true) {
      char c;
      int i;
      if (fscanf(f, "%c%d", &c, &i) != 2) {
        break;
      }
      // printf("%c%d\n", c, i);

      for (int j = 0; j < i; j++) {
        if (c == 'L') x--;
        if (c == 'R') x++;
        if (c == 'U') y--;
        if (c == 'D') y++;
        if (y >= BUF || y < 0 || x >= BUF || x < 0) {
          printf("!!! %d,%d\n", x, y);
          return 0;
        }
        grid[y][x] = 1;
        // printf("1 %d,%d\n", x, y);
      }

      fscanf(f, ",");
    }
    fscanf(f, "\n");

    x = y = BUF/2;

    int closestIntersectionDistance = 99999;

    while (true) {
      char c;
      int i;
      if (fscanf(f, "%c%d", &c, &i) != 2) {
        break;
      }

      for (int j = 0; j < i; j++) {
        if (c == 'L') x--;
        if (c == 'R') x++;
        if (c == 'U') y--;
        if (c == 'D') y++;
        if (y >= BUF || y < 0 || x >= BUF || x < 0) {
          printf("!!! %d,%d\n", x, y);
          return 0;
        }
        // printf("2 %d,%d = %d\n", x, y, grid[y][x]);
        if (grid[y][x] == 1) {
          int dist = (x > BUF/2 ? x - BUF/2 : BUF/2 - x) + (y > BUF/2 ? y - BUF/2 : BUF/2 - y);
          if (dist < closestIntersectionDistance) {
            closestIntersectionDistance = dist;
          }
        }
        grid[y][x] = 2;
      }
      fscanf(f, ",");
    }


    printf("= %d\n", closestIntersectionDistance);
    return 0;
  }
#+END_SRC

#+RESULTS:
: = 221

 - 11917 too high <2019-12-03 Tue 19:27>
 - 211 correct <2019-12-03 Tue 19:33>
** part 2
#+BEGIN_SRC cpp :results output
  #include <stdio.h>
  #include <stdlib.h>
  #define BUF 30000
  int main(int argc, char **args) {
    // char grid[BUF][BUF] = { 0 };

    int **grid = (int **) malloc(BUF * sizeof(int *));
    for (int i = 0; i < BUF; i++) {
      grid[i] = (int *) malloc(BUF * sizeof(int));
      for (int j = 0; j < BUF; j++) {
        grid[i][j] = 0;
      }
    }

    FILE *f = fopen("03.txt", "r");
    int x = BUF/2;
    int y = BUF/2;
    int step = 1;
    while (true) {
      char c;
      int i;
      if (fscanf(f, "%c%d", &c, &i) != 2) {
        break;
      }
      // printf("%c%d\n", c, i);

      for (int j = 0; j < i; j++) {
        if (c == 'L') x--;
        if (c == 'R') x++;
        if (c == 'U') y--;
        if (c == 'D') y++;
        if (y >= BUF || y < 0 || x >= BUF || x < 0) {
          printf("!!! %d,%d\n", x, y);
          return 0;
        }
        if (grid[y][x] == 0) {
          grid[y][x] = step;
        }
        step++;
        // printf("1 %d,%d\n", x, y);
      }

      fscanf(f, ",");
    }
    fscanf(f, "\n");

    x = y = BUF/2;

    int minimumSteps = 999999;

    step = 1;
    while (true) {
      char c;
      int i;
      if (fscanf(f, "%c%d", &c, &i) != 2) {
        break;
      }

      for (int j = 0; j < i; j++) {
        if (c == 'L') x--;
        if (c == 'R') x++;
        if (c == 'U') y--;
        if (c == 'D') y++;
        if (y >= BUF || y < 0 || x >= BUF || x < 0) {
          printf("!!! %d,%d\n", x, y);
          return 0;
        }
        // printf("2 %d,%d = %d\n", x, y, grid[y][x]);
        if (grid[y][x] >= 1) {
          if (grid[y][x] + step < minimumSteps) {
            minimumSteps = grid[y][x] + step;
          }
        }
        step++;
      }
      fscanf(f, ",");
    }


    printf("= %d\n", minimumSteps);
    return 0;
  }
#+END_SRC

#+RESULTS:
: = 18542

 - 18542 correct <2019-12-03 Tue 19:39> 
* day 4
** puzzle
--- Day 4: Secure Container ---

You arrive at the Venus fuel depot only to discover it's protected by a password. The Elves had written the password on a sticky note, but someone threw it out.

However, they do remember a few key facts about the password:

    It is a six-digit number.
    The value is within the range given in your puzzle input.
    Two adjacent digits are the same (like 22 in 122345).
    Going from left to right, the digits never decrease; they only ever increase or stay the same (like 111123 or 135679).

Other than the range rule, the following are true:

    111111 meets these criteria (double 11, never decreases).
    223450 does not meet these criteria (decreasing pair of digits 50).
    123789 does not meet these criteria (no double).

How many different passwords within the range given in your puzzle input meet these criteria?

Your puzzle answer was 1169.
--- Part Two ---

An Elf just remembered one more important detail: the two adjacent matching digits are not part of a larger group of matching digits.

Given this additional criterion, but still ignoring the range rule, the following are now true:

    112233 meets these criteria because the digits never decrease and all repeated digits are exactly two digits long.
    123444 no longer meets the criteria (the repeated 44 is part of a larger group of 444).
    111122 meets the criteria (even though 1 is repeated more than twice, it still contains a double 22).

How many different passwords within the range given in your puzzle input meet all of the criteria?

Your puzzle answer was 757.

Both parts of this puzzle are complete! They provide two gold stars: **
** part 1
 - <2019-12-04 Wed 18:20>
#+BEGIN_SRC cpp :results output
  #include <stdio.h>
  int main(int argc, char **args) {
      char s[1024];
      int valids = 0;
      for (int i = 236491; i <= 713787; i++) {
          sprintf(s, "%d", i);
          int foundDuplicate = 0;
          int increasing = 1;
          int prev = s[0];
          for (int j = 1; s[j] != 0; j++) {
              if (prev == s[j]) foundDuplicate = 1;
              if (prev > s[j]) { 
                increasing = 0; 
                break; 
              }
              prev = s[j];
          }
          if (foundDuplicate && increasing) {
              //printf("= %d\n", i);
              valids++;
          }
      }
      printf("= %d\n", valids);
      return 0;
  }
#+END_SRC

#+RESULTS:
: = 1169

 - 1169 correct <2019-12-04 Wed 18:28>
** part 2
#+BEGIN_SRC cpp :results output
  #include <stdio.h>
  int main(int argc, char **args) {
      char s[1024];
      int valids = 0;
      for (int i = 236491; i <= 713787; i++) {
      //{ int i = 111122;
          sprintf(s, "%d", i);
          int foundDuplicate = 0;
          int increasing = 1;
          for (int j = 1; s[j] != 0; j++) {
            if (s[j] == s[j-1]) {
              if (j >= 2 && s[j-2] == s[j])
                ; // no
              else if (s[j+1] == s[j])
                ; // no
              else
                foundDuplicate = 1;
            }
            if (s[j-1] > s[j]) {
                increasing = 0; 
                break; 
              }
          }
          if (foundDuplicate && increasing) {
              //printf("= %d\n", i);
              valids++;
          }
      }
      printf("= %d\n", valids);
      return 0;
  }
#+END_SRC

#+RESULTS:
: = 757

 - 487 too low <2019-12-04 Wed 18:30>
 - 1165 too high <2019-12-04 Wed 18:34>
 - 757 right answer <2019-12-04 Wed 18:45>
