13:
	rustc -o a 13.rs && ./a && rm a
12:
	rustc -o a 12.rs && ./a && rm a
11:
	rustc -o a 11.rs && ./a && rm a
10:
	rustc -o a 10.rs && ./a && rm a
09:
	rustc -o a 09.rs && ./a && rm a
08:
	rustc -o a 08.rs && ./a && rm a
07:
	rustc -o a 07.rs && ./a && rm a
06:
	rustc -o a 06.rs && ./a && rm a
05:
	rustc -o a 05.rs && ./a && rm a
04:
	rustc -o a 04.rs && ./a && rm a
03:
	rustc -o a 03.rs && ./a && rm a
02:
	rustc -o a 02.rs && ./a && rm a
01:
	rustc -o a 01.rs && ./a && rm a
