* setup
(require 'ob-org)
(require 'ob-python)
** stdout/stderr on bad exit-code
#+BEGIN_SRC elisp
(defun org-babel-eval (cmd body)
  "Run CMD on BODY.
If CMD succeeds then return its results, otherwise display
STDERR with `org-babel-eval-error-notify'."
  (let ((err-buff (get-buffer-create " *Org-Babel Error*")) exit-code)
    (with-current-buffer err-buff (erase-buffer))
    (with-temp-buffer
      (insert body)
      (setq exit-code
	    (org-babel--shell-command-on-region
	     (point-min) (point-max) cmd err-buff))
      (if (or (not (numberp exit-code)) (> exit-code 0))
	  (progn
	    (with-current-buffer err-buff
	      (org-babel-eval-error-notify exit-code (buffer-string)))
	    (save-excursion
	      (when (get-buffer org-babel-error-buffer-name)
		(with-current-buffer org-babel-error-buffer-name
		  (unless (derived-mode-p 'compilation-mode)
		    (compilation-mode))
		  ;; Compilation-mode enforces read-only, but Babel expects the buffer modifiable.
		  (setq buffer-read-only nil))))
	    (concat (buffer-string) "STDERR:\n" (with-current-buffer err-buff (buffer-string))))
	(buffer-string)))))
#+END_SRC
* make work
 - tangle file: C-c C-v t
 - C-c C-c code src

* day 1
** puzzle
--- Day 1: Report Repair ---

After saving Christmas five years in a row, you've decided to take a vacation at a nice resort on a tropical island. Surely, Christmas will go on without you.

The tropical island has its own currency and is entirely cash-only. The gold coins used there have a little picture of a starfish; the locals just call them stars. None of the currency exchanges seem to have heard of them, but somehow, you'll need to find fifty of these coins by the time you arrive so you can pay the deposit on your room.

To save your vacation, you need to get all fifty stars by December 25th.

Collect stars by solving puzzles. Two puzzles will be made available on each day in the Advent calendar; the second puzzle is unlocked when you complete the first. Each puzzle grants one star. Good luck!

Before you leave, the Elves in accounting just need you to fix your expense report (your puzzle input); apparently, something isn't quite adding up.

Specifically, they need you to find the two entries that sum to 2020 and then multiply those two numbers together.

For example, suppose your expense report contained the following:

1721
979
366
299
675
1456

In this list, the two entries that sum to 2020 are 1721 and 299. Multiplying them together produces 1721 * 299 = 514579, so the correct answer is 514579.

Of course, your expense report is much larger. Find the two entries that sum to 2020; what do you get if you multiply them together?

Your puzzle answer was 471019.
--- Part Two ---

The Elves in accounting are thankful for your help; one of them even offers you a starfish coin they had left over from a past vacation. They offer you a second one if you can find three numbers in your expense report that meet the same criteria.

Using the above example again, the three entries that sum to 2020 are 979, 366, and 675. Multiplying them together produces the answer, 241861950.

In your expense report, what is the product of the three entries that sum to 2020?

Your puzzle answer was 103927824.

Both parts of this puzzle are complete! They provide two gold stars: **
** star 1
 - <2020-12-08 Tue 19:24>
#+BEGIN_SRC cpp :results output
#include <stdio.h>

int main() {
  FILE *f = fopen("01.txt", "r");
  int a, b;
  while (1 == fscanf(f, "%d", &a)) {
    FILE *f2 = fopen("01.txt", "r");
    while (1 == fscanf(f2, "%d", &b)) {
      if (a + b == 2020) {
        printf("=%d\n", a*b);
        return 0;
      }
    }
    fclose(f2);
  }
  printf("sdasd\n");
  return 0;
}
#+END_SRC

#+RESULTS:
: =471019
 - <2020-12-08 Tue 19:28>

** star 2
- <2020-12-08 Tue 19:28>
#+BEGIN_SRC cpp :results output
#include <stdio.h>

int main() {
  FILE *f = fopen("01.txt", "r");
  int a, b, c;
  while (1 == fscanf(f, "%d", &a)) {
    FILE *f2 = fopen("01.txt", "r");
    while (1 == fscanf(f2, "%d", &b)) {
      FILE *f3 = fopen("01.txt", "r");
      while (1 == fscanf(f3, "%d", &c)) {
        if (a + b + c == 2020) {
          printf("=%d\n", a*b*c);
          return 0;
          }
      }
      fclose(f3);
    }
    fclose(f2);
  }
  printf("sdasd\n");
  return 0;
}
#+END_SRC

#+RESULTS:
: =103927824
 - <2020-12-08 Tue 19:30>
* day 2
** puzzle
--- Day 2: Password Philosophy ---

Your flight departs in a few days from the coastal airport; the easiest way down to the coast from here is via toboggan.

The shopkeeper at the North Pole Toboggan Rental Shop is having a bad day. "Something's wrong with our computers; we can't log in!" You ask if you can take a look.

Their password database seems to be a little corrupted: some of the passwords wouldn't have been allowed by the Official Toboggan Corporate Policy that was in effect when they were chosen.

To try to debug the problem, they have created a list (your puzzle input) of passwords (according to the corrupted database) and the corporate policy when that password was set.

For example, suppose you have the following list:

1-3 a: abcde
1-3 b: cdefg
2-9 c: ccccccccc

Each line gives the password policy and then the password. The password policy indicates the lowest and highest number of times a given letter must appear for the password to be valid. For example, 1-3 a means that the password must contain a at least 1 time and at most 3 times.

In the above example, 2 passwords are valid. The middle password, cdefg, is not; it contains no instances of b, but needs at least 1. The first and third passwords are valid: they contain one a or nine c, both within the limits of their respective policies.

How many passwords are valid according to their policies?

Your puzzle answer was 550.
--- Part Two ---

While it appears you validated the passwords correctly, they don't seem to be what the Official Toboggan Corporate Authentication System is expecting.

The shopkeeper suddenly realizes that he just accidentally explained the password policy rules from his old job at the sled rental place down the street! The Official Toboggan Corporate Policy actually works a little differently.

Each policy actually describes two positions in the password, where 1 means the first character, 2 means the second character, and so on. (Be careful; Toboggan Corporate Policies have no concept of "index zero"!) Exactly one of these positions must contain the given letter. Other occurrences of the letter are irrelevant for the purposes of policy enforcement.

Given the same example list from above:

    1-3 a: abcde is valid: position 1 contains a and position 3 does not.
    1-3 b: cdefg is invalid: neither position 1 nor position 3 contains b.
    2-9 c: ccccccccc is invalid: both position 2 and position 9 contain c.

How many passwords are valid according to the new interpretation of the policies?

Your puzzle answer was 634.

Both parts of this puzzle are complete! They provide two gold stars: **
** star 1
<2020-12-08 Tue 19:30>
#+BEGIN_SRC cpp :results output
#include <stdio.h>
int main() {
  FILE *f = fopen("02.txt", "r");
  int min, max;
  char c;
  char password[200] = {0};
  int valids = 0;
  while (4 == fscanf(f, "%d-%d %c: %s", &min, &max, &c, password)) {
    //printf("%d-%d %c: '%s'\n", min, max, c, password);

    int count = 0;
    for (int i = 0; password[i]; i++) {
      if (password[i] == c) count++;
    }
    if (count >= min && count <= max) {
      valids++;
    }
  }
  printf("= %d\n", valids);
  return 0;
}
#+END_SRC

#+RESULTS:
: = 550

- <2020-12-08 Tue 19:40>
** star 2
- <2020-12-08 Tue 19:40>
#+BEGIN_SRC cpp :results output
#include <stdio.h>
int main() {
  FILE *f = fopen("02.txt", "r");
  int min, max;
  char c;
  char password[200] = {0};
  int valids = 0;
  while (4 == fscanf(f, "%d-%d %c: %s", &min, &max, &c, password)) {
    //printf("%d-%d %c: '%s'\n", min, max, c, password);
    if (password[min-1] == c ^ password[max-1] == c) valids++;
  }
  printf("= %d\n", valids);
  return 0;
}
#+END_SRC

#+RESULTS:
: = 634


- <2020-12-08 Tue 19:41>
* day 3
** puzzle
--- Day 3: Toboggan Trajectory ---

With the toboggan login problems resolved, you set off toward the airport. While travel by toboggan might be easy, it's certainly not safe: there's very minimal steering and the area is covered in trees. You'll need to see which angles will take you near the fewest trees.

Due to the local geology, trees in this area only grow on exact integer coordinates in a grid. You make a map (your puzzle input) of the open squares (.) and trees (#) you can see. For example:

..##.......
#...#...#..
.#....#..#.
..#.#...#.#
.#...##..#.
..#.##.....
.#.#.#....#
.#........#
#.##...#...
#...##....#
.#..#...#.#

These aren't the only trees, though; due to something you read about once involving arboreal genetics and biome stability, the same pattern repeats to the right many times:

..##.........##.........##.........##.........##.........##.......  --->
#...#...#..#...#...#..#...#...#..#...#...#..#...#...#..#...#...#..
.#....#..#..#....#..#..#....#..#..#....#..#..#....#..#..#....#..#.
..#.#...#.#..#.#...#.#..#.#...#.#..#.#...#.#..#.#...#.#..#.#...#.#
.#...##..#..#...##..#..#...##..#..#...##..#..#...##..#..#...##..#.
..#.##.......#.##.......#.##.......#.##.......#.##.......#.##.....  --->
.#.#.#....#.#.#.#....#.#.#.#....#.#.#.#....#.#.#.#....#.#.#.#....#
.#........#.#........#.#........#.#........#.#........#.#........#
#.##...#...#.##...#...#.##...#...#.##...#...#.##...#...#.##...#...
#...##....##...##....##...##....##...##....##...##....##...##....#
.#..#...#.#.#..#...#.#.#..#...#.#.#..#...#.#.#..#...#.#.#..#...#.#  --->

You start on the open square (.) in the top-left corner and need to reach the bottom (below the bottom-most row on your map).

The toboggan can only follow a few specific slopes (you opted for a cheaper model that prefers rational numbers); start by counting all the trees you would encounter for the slope right 3, down 1:

From your starting position at the top-left, check the position that is right 3 and down 1. Then, check the position that is right 3 and down 1 from there, and so on until you go past the bottom of the map.

The locations you'd check in the above example are marked here with O where there was an open square and X where there was a tree:

..##.........##.........##.........##.........##.........##.......  --->
#..O#...#..#...#...#..#...#...#..#...#...#..#...#...#..#...#...#..
.#....X..#..#....#..#..#....#..#..#....#..#..#....#..#..#....#..#.
..#.#...#O#..#.#...#.#..#.#...#.#..#.#...#.#..#.#...#.#..#.#...#.#
.#...##..#..X...##..#..#...##..#..#...##..#..#...##..#..#...##..#.
..#.##.......#.X#.......#.##.......#.##.......#.##.......#.##.....  --->
.#.#.#....#.#.#.#.O..#.#.#.#....#.#.#.#....#.#.#.#....#.#.#.#....#
.#........#.#........X.#........#.#........#.#........#.#........#
#.##...#...#.##...#...#.X#...#...#.##...#...#.##...#...#.##...#...
#...##....##...##....##...#X....##...##....##...##....##...##....#
.#..#...#.#.#..#...#.#.#..#...X.#.#..#...#.#.#..#...#.#.#..#...#.#  --->

In this example, traversing the map using this slope would cause you to encounter 7 trees.

Starting at the top-left corner of your map and following a slope of right 3 and down 1, how many trees would you encounter?

Your puzzle answer was 156.
--- Part Two ---

Time to check the rest of the slopes - you need to minimize the probability of a sudden arboreal stop, after all.

Determine the number of trees you would encounter if, for each of the following slopes, you start at the top-left corner and traverse the map all the way to the bottom:

    Right 1, down 1.
    Right 3, down 1. (This is the slope you already checked.)
    Right 5, down 1.
    Right 7, down 1.
    Right 1, down 2.

In the above example, these slopes would find 2, 7, 3, 4, and 2 tree(s) respectively; multiplied together, these produce the answer 336.

What do you get if you multiply together the number of trees encountered on each of the listed slopes?

Your puzzle answer was 3521829480.

Both parts of this puzzle are complete! They provide two gold stars: **
** star 1
 - <2020-12-08 Tue 19:42>
#+BEGIN_SRC cpp :results output
  #include <stdio.h>
  int main() {
    FILE *f = fopen("03.txt", "r");
    char map[1000][1000] = {0};
    char c;
    printf("1\n");
    int width = 0;
    {
      int x = 0, y = 0;
      while ((c = fgetc(f)) != EOF) {
        if (c == '\n') { map[y][x] = 0; width = x; x = 0; y++; }
        else { map[y][x] = c; x++; }
      }
    }

    int trees = 0;
    int x = 0, y = 0;
    while (map[y][0]) {
      x = (x+3) % width; y += 1;
      if (map[y][x] == '#') trees++;
    }

    printf("=%d\n", trees);
    return 0;
  }
#+END_SRC

#+RESULTS:
: 1
: =156

 - <2020-12-08 Tue 19:54>
** star 2
 - <2020-12-08 Tue 19:54>
#+BEGIN_SRC cpp :results output
  #include <stdio.h>
  long trees(char map[1000][1000], int width, int dx, int dy) {
    int trees = 0;
    int x = 0, y = 0;
    while (map[y][0]) {
      x = (x+dx) % width; y += dy;
      if (map[y][x] == '#') trees++;
    }
    return trees;
  }
  int main() {
    FILE *f = fopen("03.txt", "r");
    char map[1000][1000] = {0};
    char c;
    printf("1\n");
    int width = 0;
    {
      int x = 0, y = 0;
      while ((c = fgetc(f)) != EOF) {
        if (c == '\n') { map[y][x] = 0; width = x; x = 0; y++; }
        else { map[y][x] = c; x++; }
      }
    }
    
    printf("=%ld\n", trees(map, width, 1, 1) 
                  * trees(map, width, 3, 1) 
                  * trees(map, width, 5, 1) 
                  * trees(map, width, 7, 1) 
                  * trees(map, width, 1, 2));
    //printf("=%d\n", trees);
    return 0;
  }
#+END_SRC

#+RESULTS:
: 1
: =3521829480

 - <2020-12-08 Tue 19:58>
